import {
  accountActivation,
  changePassword,
  createUserRole,
  deleteUserRole,
  forgetPassword,
  login,
  register,
  resetPassword,
  updateProfile,
  updateUserPermission,
  updateUserRole,
  updateUserRoleInfo,
  verifyEmail,
} from '../../controllers';
export const userMutationsResolver = {
  Mutation: {
    changePassword,
    createUserRole,
    deleteUserRole,
    updateUserRoleInfo,
    forgetPassword,
    login,
    register,
    resetPassword,
    updateUserPermission,
    updateUserRole,
    updateProfile,
    accountActivation,
    verifyEmail,
  },
};
