name: Test Bun Installation

on:
  workflow_dispatch:

jobs:
  test-bun:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Check repository structure
        run: |
          echo "Repository structure:"
          ls -la
          echo "Checking package.json files:"
          find . -name "package.json" -not -path "*/node_modules/*" -type f

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Test Bun in root directory
        run: |
          echo "Current directory: $(pwd)"
          if [ -f "package.json" ]; then
            echo "Root package.json found, running bun --version"
            bun --version
          else
            echo "No package.json in root directory"
          fi
      
      - name: Test Bun in users directory
        run: |
          if [ -d "users" ]; then
            cd users
            echo "Current directory: $(pwd)"
            if [ -f "package.json" ]; then
              echo "users/package.json found, running bun --version"
              bun --version
            else
              echo "No package.json in users directory"
            fi
          else
            echo "users directory not found"
          fi
      
      - name: Test Bun in media directory
        run: |
          if [ -d "media" ]; then
            cd media
            echo "Current directory: $(pwd)"
            if [ -f "package.json" ]; then
              echo "media/package.json found, running bun --version"
              bun --version
            else
              echo "No package.json in media directory"
            fi
          else
            echo "media directory not found"
          fi
      
      - name: Test Bun in product directory
        run: |
          if [ -d "product" ]; then
            cd product
            echo "Current directory: $(pwd)"
            if [ -f "package.json" ]; then
              echo "product/package.json found, running bun --version"
              bun --version
            else
              echo "No package.json in product directory"
            fi
          else
            echo "product directory not found"
          fi
